version: '3.8'

volumes:
  db-data:
    name: pico-db
    driver: local

services:
  backend:
    build:
      context: ..
      dockerfile: .docker/backend.Dockerfile
    ports:
      - 8000:8000
    environment:
      LOGIN_API_URL: http://login:7002
      LOGIN_API_KEY: not-used
      PLS_API_URL: https://pls.datasektionen.se/api
      MONGO_URL: mongodb://mongo:27017/pico
      NODE_ENV: development
    develop:
      watch:
        - action: rebuild
          path: ../
  frontend:
    build:
      context: ../client
      dockerfile: ../.docker/frontend.Dockerfile
    ports:
      - 3000:3000
    environment:
      REACT_APP_LOGIN_API_URL: http://localhost:7002
      REACT_APP_API_URL: http://localhost:8000
    develop:
      watch:
        - action: sync
          path: ../client
          target: /app
        - action: rebuild
          path: ../client/package.json
  login:
    image: ghcr.io/datasektionen/nyckeln-under-dorrmattan
    ports:
      - 7002:7002
    environment:
      # Since we're using the real pls, it's nice to use some user with a lot of priveleges. Putting
      # mine here since I'm d-sys at the time of writing.
      KTH_ID: mathm
  mongo:
    image: mongo
    restart: always
    container_name: pico-mongodb
    volumes:
      - db-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    container_name: pico-mongo-express
    ports:
      - 8081:8081
    environment:
        ME_CONFIG_MONGODB_URL: mongodb://mongo:27017
    depends_on:
      - mongo
