version: '3.8'

volumes:
  db-data:
    name: pico-db
    driver: local

services:
  app:
    image: node:16-alpine3.18
    ports:
      - 8000:8000
    volumes:
      - ../:/app
    command: su node -c "cd /app && npm i && npm run build:frontend && npm run dev"
    environment:
      LOGIN_API_URL: http://login:7002
      LOGIN_API_KEY: not-used
      PLS_API_URL: https://pls.datasektionen.se/api
      MONGO_URL: mongodb://mongo:27017/pico
      NODE_ENV: development
      REACT_APP_LOGIN_API_URL: http://localhost:7002
      REACT_APP_API_URL: http://localhost:8000
  login:
    image: ghcr.io/datasektionen/nyckeln-under-dorrmattan
    ports:
      - 7002:7002
  mongo:
    image: mongo
    restart: always
    container_name: pico-mongodb
    volumes:
      - db-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    container_name: pico-mongo-express
    ports:
      - 8081:8081
    environment:
        ME_CONFIG_MONGODB_URL: mongodb://mongo:27017
    depends_on:
      - mongo
