name: Build, deploy

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Deploy on medusa
      uses: idoberko2/dokku-deploy-github-action@v1
      with:
        ssh-private-key: ${{ secrets.MEDUSA_SSH_KEY }}
        dokku-user: 'dokku'
        remote-branch: 'master'
        dokku-host: 'medusa.datasektionen.se'
        app-name: 'dsekt.se'
